services:
  cardconjurer:
    image: nginx:stable-alpine
    ports:
      - "4242:4242"
    volumes:
      - ./:/usr/share/nginx/html/:ro
      - ./docker/app.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - cardserver

  cardserver:
    build: ./server
    environment:
      - DB_PATH=/app/data/cards.db
    volumes:
      - ./data/db:/app/data
