services:
  cardconjurer:
    image: nginx:stable-alpine
    ports:
      - "4242:4242"
    volumes:
      - ./:/usr/share/nginx/html/:ro
      - ./docker/app.conf:/etc/nginx/nginx.conf:ro
      - ./data/card_images:/usr/share/nginx/html/card-images:ro
    depends_on:
      - cardserver

  cardserver:
    build: ./server
    environment:
      - DB_PATH=/app/data/cards.db
      - IMAGES_DIR=/app/card_images
    volumes:
      - ./data/db:/app/data
      - ./data/card_images:/app/card_images
